<a href="https://colab.research.google.com/github/AliAbdullah0/Learning-PyTorch/blob/main/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **0_PyTorch_Fundamentals**

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

In [ ]:
## Introduction To Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

In [ ]:
scalar.ndim

In [ ]:
scalar.item()

In [ ]:
# Vector

In [ ]:
vector = torch.tensor([7,7])
vector

In [ ]:
vector.ndim

In [ ]:
vector.shape

In [ ]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]
                      ])
MATRIX

In [ ]:
MATRIX.ndim

In [ ]:
MATRIX[0][1]

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR


In [ ]:
TENSOR.shape

In [ ]:
TENSOR[0]

In [ ]:
TENSOR2 = torch.tensor([[[4,5,6],
             [7,8,9],
             [10,5,6],
             [5,2,5]]])
TENSOR2.shape

**Random Tensors**

Why Random tensors?

They are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Creating Random tensors of size (3,4)

In [ ]:
random_tensor = torch.rand(size=(3,224,224))
random_tensor.shape, random_tensor.dtype

## **Zeros** and **Ones**

In [ ]:
zero_tensor = torch.zeros(size=(1,5,3))
zero_tensor

In [ ]:
one_tensor = torch.ones(size=(5,5))
one_tensor

In [ ]:
one_tensor.ndim,one_tensor.shape

In [ ]:
random_tensor.dtype

**Range Of Tensors** and **Tensors Like**

In [ ]:
one_to_ten = torch.arange(1,11)

In [ ]:
# Creating Tensors like (used to create a copy of a tensor with different values)

In [ ]:
ten_zeros = torch.zeros_like(one_to_ten)

In [ ]:
ten_zeros

 # **Tensor Data Types**

In [ ]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # tells what is datatype
                               device="cpu", # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor operations

In [ ]:
float_32_tensor.dtype

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)

In [ ]:
float_16_tensor.dtype

In [ ]:
float_32_tensor.dtype
float_16_tensor,float_32_tensor

In [ ]:
float_16_tensor * float_32_tensor

In [ ]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)

In [ ]:
int_32_tensor

In [ ]:
float_32_tensor * int_32_tensor

In [ ]:
## Getting information from tensors
some_tensor = torch.rand(3,4)
print(f'Data type of tensor {some_tensor.dtype}')
print(f'Device type of tensor {some_tensor.device}')
print(f'Shape of tensor {some_tensor.shape}')
print(f'Number of dimensions of a tensor {some_tensor.ndim}')


# **Manipulating Tensors** (tensor operations)


*   Addition
*   Subtraction
*   Multiplication ( element-wise )
*   Division
*   Matrix multiplication





In [ ]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

In [ ]:
# multiply tensor by 10
tensor * 10

In [ ]:
# subtract 10
tensor,tensor - 10

In [ ]:
# Inbuilt functions
torch.mul(tensor,10)

In [ ]:
torch.add(tensor,5)

# Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1.Element wise Multiplication<br>
2.Matrix multiplication (dot product)

In [97]:
newTensor = torch.tensor([1,2,3])

In [98]:
newTensor

tensor([1, 2, 3])

In [99]:
newTensor * newTensor

tensor([1, 4, 9])

In [102]:
torch.matmul(newTensor,newTensor)

(tensor([1, 2, 3]), tensor(14))