# **0_PyTorch_Fundamentals**

In [99]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu124


In [100]:
## Introduction To Tensors

In [101]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [102]:
scalar.ndim

0

In [103]:
scalar.item()

7

In [104]:
# Vector

In [105]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [106]:
vector.ndim

1

In [107]:
vector.shape

torch.Size([2])

In [108]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]
                      ])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [109]:
MATRIX.ndim

2

In [110]:
MATRIX[0][1]

tensor(8)

In [111]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR


tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [112]:
TENSOR.shape

torch.Size([1, 3, 3])

In [113]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [114]:
TENSOR2 = torch.tensor([[[4,5,6],
             [7,8,9],
             [10,5,6],
             [5,2,5]]])
TENSOR2.shape

torch.Size([1, 4, 3])

**Random Tensors**

Why Random tensors?

They are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [115]:
# Creating Random tensors of size (3,4)

In [116]:
random_tensor = torch.rand(size=(3,224,224))
random_tensor.shape, random_tensor.dtype

(torch.Size([3, 224, 224]), torch.float32)

## **Zeros** and **Ones**

In [117]:
zero_tensor = torch.zeros(size=(1,5,3))
zero_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [118]:
one_tensor = torch.ones(size=(5,5))
one_tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [119]:
one_tensor.ndim,one_tensor.shape

(2, torch.Size([5, 5]))

In [120]:
random_tensor.dtype

torch.float32

**Range Of Tensors** and **Tensors Like**

In [121]:
one_to_ten = torch.arange(1,11)

In [122]:
# Creating Tensors like (used to create a copy of a tensor with different values)

In [123]:
ten_zeros = torch.zeros_like(one_to_ten)

In [124]:
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

 # **Tensor Data Types**

In [125]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None, # tells what is datatype
                               device="cpu", # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor operations

In [126]:
float_32_tensor.dtype

torch.float32

In [127]:
float_16_tensor = float_32_tensor.type(torch.half)

In [128]:
float_16_tensor.dtype

torch.float16

In [129]:
float_32_tensor.dtype
float_16_tensor,float_32_tensor

(tensor([3., 6., 9.], dtype=torch.float16), tensor([3., 6., 9.]))

In [130]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [131]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.long)

In [132]:
int_32_tensor

tensor([3, 6, 9])

In [133]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

In [134]:
## Getting information from tensors
some_tensor = torch.rand(3,4)
print(f'Data type of tensor {some_tensor.dtype}')
print(f'Device type of tensor {some_tensor.device}')
print(f'Shape of tensor {some_tensor.shape}')
print(f'Number of dimensions of a tensor {some_tensor.ndim}')


Data type of tensor torch.float32
Device type of tensor cpu
Shape of tensor torch.Size([3, 4])
Number of dimensions of a tensor 2


# **Manipulating Tensors** (tensor operations)


*   Addition
*   Subtraction
*   Multiplication ( element-wise )
*   Division
*   Matrix multiplication





In [135]:
# create a tensor and add 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [136]:
# multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [137]:
# subtract 10
tensor,tensor - 10

(tensor([1, 2, 3]), tensor([-9, -8, -7]))

In [138]:
# Inbuilt functions
torch.mul(tensor,10)

tensor([10, 20, 30])

In [139]:
torch.add(tensor,5)

tensor([6, 7, 8])

# Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning

1.Element wise Multiplication<br>
2.Matrix multiplication (dot product)

In [140]:
newTensor = torch.tensor([1,2,3])

In [141]:
newTensor

tensor([1, 2, 3])

In [142]:
newTensor * newTensor

tensor([1, 4, 9])

In [143]:
torch.matmul(newTensor,newTensor)

tensor(14)

In [144]:
%%time
value = 0
for i in range(len(newTensor)):
  value += newTensor[i] * newTensor[i]
value

CPU times: user 275 µs, sys: 0 ns, total: 275 µs
Wall time: 287 µs


tensor(14)

In [145]:
%%time
torch.matmul(newTensor,newTensor)

CPU times: user 102 µs, sys: 3 µs, total: 105 µs
Wall time: 131 µs


tensor(14)

## One of the most common errors in deep learning are


*   The **inner dimensions** must match
*   The resulting matrix has the shape of the **outer dimensions**



In [146]:
tensor1 = torch.rand(2,3)
tensor1

tensor([[0.4739, 0.2180, 0.2217],
        [0.2293, 0.5890, 0.9545]])

In [147]:
tensor2 = torch.rand(3,2)
tensor2

tensor([[0.8259, 0.6724],
        [0.6361, 0.5690],
        [0.6492, 0.4968]])

In [148]:
torch.matmul(tensor1,tensor2)

tensor([[0.6740, 0.5528],
        [1.1837, 0.9636]])

In [149]:
torch.matmul(torch.rand(3,2),torch.rand(2,2))

tensor([[0.9101, 0.8143],
        [0.7259, 0.6455],
        [0.3915, 0.3379]])

# Shape Errors

In [150]:
tensor_A = torch.tensor([[1,2],
                         [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                         [8,11],
                        [9,12]])

# TO FIX TENSOR SHAPE ISSUES WE CAN MUNIPULATE ONE OF OUR TENSOR SHAPES USING TRANSPOSE

In [151]:
# torch.mm(tensor_A,tensor_B) ## torch.mm is same is torch.matmul

In [152]:
# torch.mm(tensor_A,tensor_B) ## torch.mm is same is torch.matmul

In [153]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [154]:
tensor_B.T,tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [155]:
tensor_B = tensor_B.T

In [156]:
# The matrix multiplication operation works when tensor_B is transposed
torch.mm(tensor_A,tensor_B).shape ## torch.mm is same is torch.matmul

torch.Size([3, 3])

### Finding the max,mean,sum etc (tensor aggregation)

In [157]:
# Create a tensor
x = torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [158]:
# Find the min
torch.min(x),x.min()

(tensor(1), tensor(1))

In [159]:
# Find the max
torch.max(x),x.max()

(tensor(91), tensor(91))

In [160]:
# Find the mean (requires a tensor of float32 type)
torch.mean(x.type(torch.float32))

tensor(46.)

In [161]:
torch.sum(x) ,x.sum()

(tensor(460), tensor(460))

## Finding the positional min and max

In [162]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [163]:
# Find the position in tensor that has minimum value with argmin() -> returns the index position of the target tensor where minimum value occurs
x.argmin()

tensor(0)

In [164]:
x[0]

tensor(1)

In [166]:
# Find the position in tensor that has maximum value with argmax()
x.argmax()

tensor(9)

In [167]:
x[9]

tensor(91)

## Reshaping, stacking , squeezing an unsqueezing tensors

<li>Reshaping - reshapes an input tensor to a defined shape</li>
<li>View - return a view of an input tensor of a certain shape but keep the same memory as the original tensor</li>
<li>Stacking - combine multiple tensors on top of each other</li>
<li>Squeeze - removes all `1` dimensions from a tensor</li>
<li>Unsqueeze - add a `1` imension to a target tensor</li>
<li>Permute - return a view of the input with dimensions permuted (swapped) in a certain way.</li>

In [188]:
# Create a tensor
x = torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [189]:
# Reshape
x_reshaped = x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [193]:
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [194]:
# changing z changes x (because a view of a tensor shares the same memory as the original input)

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [201]:
z[:,0] = 5
z,x

tensor([5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [209]:
z

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [212]:
# Stcak functions on top of each other
z = torch.arange(1,10)
z_stacked = torch.stack([z,z,z,z],dim=1)
z_stacked

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])