# **0_PyTorch_Fundamentals**

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

In [ ]:
## Introduction To Tensors

In [ ]:
# scalar
scalar = torch.tensor(7)
scalar

In [ ]:
scalar.ndim

In [ ]:
scalar.item()

In [ ]:
# Vector

In [ ]:
vector = torch.tensor([7,7])
vector

In [ ]:
vector.ndim

In [ ]:
vector.shape

In [ ]:
# Matrix
MATRIX = torch.tensor([[7,8],
                       [9,10]
                      ])
MATRIX

In [ ]:
MATRIX.ndim

In [ ]:
MATRIX[0][1]

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR


In [ ]:
TENSOR.shape

In [ ]:
TENSOR[0]

In [ ]:
TENSOR2 = torch.tensor([[[4,5,6],
             [7,8,9],
             [10,5,6],
             [5,2,5]]])
TENSOR2.shape

**Random Tensors**

Why Random tensors?

They are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [ ]:
# Creating Random tensors of size (3,4)

In [29]:
random_tensor = torch.rand(size=(3,224,224))
random_tensor.shape, random_tensor.dtype

(torch.Size([224, 224, 3]), torch.float32)

## **Zeros** and **Ones**

In [30]:
zero_tensor = torch.zeros(size=(1,5,3))
zero_tensor

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]])

In [31]:
one_tensor = torch.ones(size=(5,5))
one_tensor

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [32]:
one_tensor.ndim,one_tensor.shape

(2, torch.Size([5, 5]))

In [33]:
random_tensor.dtype

torch.float32

**Range Of Tensors** and **Tensors Like**

In [37]:
torch.arange(1,11,2)

tensor([1, 3, 5, 7, 9])